# Generated by Django 5.1 on 2024-08-08 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886, 'Год выпуска не может быть меньше 1886'), django.core.validators.MaxValueValidator(2024, 'Год выпуска не может быть больше текущего года')])),
                ('fuel_type', models.CharField(choices=[('PET', 'бензин'), ('DIE', 'дизель'), ('ELE', 'электричество'), ('HYB', 'гибрид')], max_length=3)),
                ('transmission', models.CharField(choices=[('MAN', 'механическая'), ('AUT', 'автоматическая'), ('CVT', 'вариатор'), ('DCT', 'робот')], max_length=3)),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть отрицательной')])),
            ],
        ),
    ]
