# Generated by Django 5.1 on 2024-08-09 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_fuel_type_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('бензин', 'Petrol'), ('дизель', 'Diesel'), ('электричество', 'Electric'), ('гибрид', 'Hybrid')], max_length=13),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'The price cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('механическая', 'Manual'), ('автоматическая', 'Automatic'), ('вариатор', 'Cvt'), ('робот', 'Dct')], max_length=14),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886, 'The year of release cannot be less than 1886'), django.core.validators.MaxValueValidator(2024, 'The year of release cannot be more than the current year')]),
        ),
    ]
